#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"

// Elevator
#define ELEVATOR_CAN 1
#define ELEVATOR_BOTTOM_DIO 0
#define ELEVATOR_COLELCT_TOTE_DIO 1
#define ELEVATOR_READY_TOTE_DIO 2
#define ELEVATOR_COLELCT_CAN_DIO 3
#define ELEVATOR_READY_CAN_DIO 4
#define ELEVATOR_TOP_DIO 5

// Drivetrain
#define DRIVE_FRONT_LEFT_CAN 2
#define DRIVE_BACK_LEFT_CAN 3
#define DRIVE_FRONT_RIGHT_CAN 4
#define DRIVE_BACK_RIGHT_CAN 5

// Collector
#define COLLECTOR_WINDOW_LEFT_CAN 6
#define COLLECTOR_WINDOW_RIGHT_CAN 7
#define COLLECTOR_LEFT_CAN 8
#define COLLECTOR_RIGHT_CAN 9

#endif
// vim: ts2:sw=2:et
